name: Deploy Bot to VPS

on:
  push:
    branches:
      - main  # Change if you're using a different branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Deploy via SSH to VPS
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_KEY }}
          port: ${{ secrets.VPS_PORT || 22 }}
          script: |
            cd /path/to/your/project  # Update this to where the bot is cloned
            git pull origin main
            npm install
            pm2 restart bionix || pm2 start index.js --name bionix
